import Head from "next/head";


/**
 * Navbar component for the Reform in Focus website.
 * Provides navigation links to various sections of the site.
 *
 * @returns {JSX.Element} The rendered Navbar component.
 */
export default function HeaderComponent() {
    return (
        <Head>
            <title>Reform In Focus</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}