import Head from "next/head";
import Navbar from "@/components/navbar";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import Article, { ArticleHeader, ArticleBody, ArticleFigure } from "@/components/article";


export default function Home() {
  return (
    <>
      <Head>
        <title>Reform in Focus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Article>
        <ArticleHeader title="Welcome to Reform in Focus" subtitle="Exploring the Path to Meaningful Change" />
        <ArticleBody articleContent="This is where the main content of the article will go. Stay tuned for more updates!" />
      </Article>
    </>
  );
}
