import Head from "next/head";
import Navbar from "@/components/navbar";

import "@/styles/globals.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Reform in Focus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main >
          <Navbar />
          <h1>Welcome to Reform in Focus</h1>
          Test
        </main>
      </div>
    </>
  );
}
